config/routes.rb
Rails.application.routes.draw do
  resources :sells
  resources :books
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true

    has_many :sells

    after_create_commit :create_chart

    private

    def create_chart
        broadcast_append_to(
           'books_charts_channel',
             partial: '/home/charts/books/chart', 
             locals: { book: self }, 
             target: 'books_charts'
            )
    end
end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :book
  validates :quantity, presence: true
  validates :day, presence: true


  after_create :set_total

  after_create_commit :update_charts

  DAYS = %w[MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY SUNDAY].freeze

  private

  def set_total
    revenue = quantity * book.price
    update(total: revenue)
  end

  def update_charts
    broadcast_replace_to('sells_charts_channel',partial: '/home/charts/days/chart',locals: {},target: 'days_chart')
    broadcast_replace_to('sells_charts_channel',partial: '/home/charts/revenue/chart',locals: {},target: 'revenue_chart')
    broadcast_replace_to('sells_charts_channel',partial: '/home/charts/books/chart',locals: { book: book},target: "book_#{book.id}")

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
      @book = Book.new
  end

  def create
    @book = Book.new book_params

    if @book.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  before_action :set_book, only: %i[create]
    def new
       @sell = Sell.new 
    end

    def create
      @sell = @book.sells.new sell_params

      if @sell.save
        respond_to do |format|
          format.turbo_stream
      end
      else
        render :new, status: :unprocessable_entity
      end
     
    end
    private

    def set_book
      @book = Book.find(params[:sell][:book_id])
    end

    def sell_params
      params.require(:sell).permit(:quantity, :day)

    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def latest_sells id
    array = Array.new

    Book.find(id).sells.each do |sell|
      array.push(sell.quantity)
    end

    array
  end 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sells_helper.rb
module SellsHelper
  def sells_per_day
    array = Array.new

    Sell::DAYS.each do |day|
      array.push([day, Sell.where(day: day).sum(:quantity)])
    end

    array
  end

  def revenue_from_sells
    array = Array.new

    Book.all.each do |book|
      array.push([book.name, book.sells.sum(:total).round(2)])
    end

    array
  end
end

app/views/books/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
  <div class="flex w-full items-center">
    <%= form_with(model: book, class: 'flex w-full items-center gap-2') do |form| %>
      <% if book.errors.any? %>
        <% book.errors.each do |error| %>
          <span class="text-white"><%= error.full_message %></span>
        <% end %>
      <% end %>

      <div class="flex items-center gap-2">
        <%= form.label :name, class: 'font-semibold text-white' %>
        <%= form.text_field :name, class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-2">
        <%= form.label :price, class: 'font-semibold text-white' %>
        <%= form.number_field :price, in: 1.0..100.0, step: :any, class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex itemse-center justify-end gap-2 ml-5">
        <%= form.submit class: 'font-semibold p-2 bg-sky-600 text-sm text-white rounded' %>
        <%= link_to 'Cancel', :back, class:'font-semibold p-2 bg-red-600 text-sm text-white rounded' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<%= render 'form', { book: @book } %>

app/views/home/charts/books/_books.html.erb
<section class="flex w-full flex-col border">
    <h3 class="text-white font-bold text-lg">Sells by book</h3>
    <div class="flex flex-col" id="books_charts">
    <% Book.all.each do |book| %>
      <%= render 'home/charts/books/chart', book: book %>
    <% end %>
    </div>
  </section>

app/views/home/charts/books/_chart.html.erb
<div data-controller="book" data-book-sells="<%= latest_sells(book.id) %>" book-id="<%= book.id %>"
class="text-white bg-white p-5 m-5 rounded" id="book_<%= book.id %>">
  <canvas id="book_chart_<%= book.id %>" style="width:100%;max-width:700px"></canvas>
</div>

app/views/home/charts/days/_chart.html.erb
<div data-controller="days" data-days-sells="<%= sells_per_day %>" id="days_chart" class="bg-white p-5 m-5 rounded">
 <canvas id="daySells" style="width:100%;max-width:700px"></canvas>   
</div>

app/views/home/charts/days/_days.html.erb
<section class="flex w-full flex-col border">
    <h3 class="text-white font-bold text-lg">Sells per day</h3>
  
    <%= render 'home/charts/days/chart' %>
  </section>

app/views/home/charts/revenue/_chart.html.erb
<div data-controller="revenue" data-revenue-sells="<%= revenue_from_sells %>" id="revenue_chart" class="bg-white p-5 m-5 rounded">
    <canvas id="revenueSells" style="width:100%;max-width:700px"></canvas>
  
    <div class="flex flex-col bg-white p-5 rounded mt-10 m-5">
      <h5 class="font-bold text-center my-5 text-xl">Sells per book</h5>

        <table class="my-5">
            <div class="flex w-full">
              <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">ID</div>
              <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">Name</div>
              <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">Revenue</div>
            </div>
      
            <div class="flex flex-col">
              <% Book.all.each do |book| %>
                <div class="flex">
                  <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center"><%= book.id %></div>
                  <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center"><%= book.name %></div>
                  <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center"><%= book.sells.sum(:total).round(2) %> USD</div>
                </div>
              <% end %>
            </div>
          </table>
            <div>
                <%= Sell.all.sum(:total).round(2) %>
            </div>
    </div>
   </div>
   

app/views/home/charts/revenue/_revenue.html.erb
<section class="flex w-full flex-col border">
    <h3 class="text-white font-bold text-lg">Revenue</h3>
  
    <%= render 'home/charts/revenue/chart' %>
  </section>

app/views/home/index.html.erb
<%= turbo_stream_from 'books_charts_channel'%>
<%= turbo_stream_from 'sells_charts_channel'%>

<main class="flex flex-col">
    <%= render 'shared/navbar' %>
  
    <section class="flex flex-col items-center justify-center w-full mt-20 mb-5">
      <div class="flex flex-col items-center">
        <h1 class="font-bold text-4xl text-white my-5">The App Store</h1>
      </div>
      <div class="flex gap-5 border-4 border-gray-200 w-full h-screen">
        <%= render 'home/charts/days/days' %>
        <%= render 'home/charts/revenue/revenue' %>
        <%= render 'home/charts/books/books' %>
      </div>
  
      
    </section>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-600">
   
      <%= yield %>

  </body>
</html>

app/views/sells/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
  <div class="flex w-full items-center">

    <%= form_with(model: sell, class: 'flex w-full items-center gap-2') do |form| %>
    <% if sell.errors.any? %>
      <% sell.errors.each do |error| %>
        <span class="text-white"><%= error.full_message %></span>
      <% end %>
    <% end %>

    <div class="flex items-center gap-2">
        <%= form.label :book_id, 'Select book:', class: 'font-semibold text-white' %>
        <%= form.select(:book_id, Book.all.collect {|book|[book.name, book.id]}, {include_blank: true},
        class: 'font-semibold rounded p-2 text-xs'
        )%>
    </div>

    <div class="flex items-center gap-2">
      <%= form.label :quantity, class: 'font-semibold text-white' %>
      <%= form.number_field :quantity, class: 'font-semibold rounded p-2 text-xs' %>
    </div>

    <div class="flex items-center gap-2">
        <%= form.label :day, 'Select day:', class: 'font-semibold text-white' %>
        <%= form.select(:day, Sell::DAYS.map {|day| [day.humanize, day]}, {include_blank: true},
        class: 'font-semibold rounded p-2 text-xs'
        )%>
    </div>

    
    <div class="flex itemse-center justify-end gap-2 ml-5">
      <%= form.submit class: 'font-semibold p-2 bg-sky-600 text-sm text-white rounded' %>
      <%= link_to 'Cancel', :back, class:'font-semibold p-2 bg-red-600 text-sm text-white rounded' %>
    </div>
  <% end %>
  </div>
<% end %>

app/views/sells/new.html.erb
<%= render 'form', sell: @sell%>

app/views/shared/_navbar.html.erb
<nav class="w-full flex bg-gray-300 items-center p-5 justify-between fixed">
    <div class="flex gap-5 items-center">
      <%= image_tag('book.png', class: 'w-12') %>
      <h3 class="font-bold text-lg text-white">The App Store</h3>
    </div>
  
    <div class="flex ">
        <%= turbo_frame_tag 'new_record_component', class: 'flex gap-5' do %>
          <%= link_to new_sell_path, id: 'sell_link', class: 'text-white font-semibold text-sm text-center bg-amber-400 text-white rounded px-4 py-2' do %>
            Add sell
          <% end %>
    
          <%= link_to new_book_path, id: 'book_link', class: 'text-white font-semibold text-sm text-center bg-cyan-400 text-white rounded px-4 py-2' do %>
            Add a new book
          <% end %>
        <% end %>
      </div>
  </nav>